In [3]:
from numpy import *
a = arange(12)
a = a.reshape(3,2,2)
print(a)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [4]:
a[1]

array([[4, 5],
       [6, 7]])

In [5]:
a[1:1]

array([], shape=(0, 2, 2), dtype=int32)

In [6]:
a[1:3]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [7]:
a[1:3:1]

array([[[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [8]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [49]:
a[1:3,0]

array([4, 8])

In [48]:
a[::,0]

array([1, 4, 8, 9])

In [18]:
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [17]:
a[:,:,1]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [47]:
a[1:3]

array([[4, 5, 6, 7, 8],
       [8, 7, 4, 5, 2]])

In [34]:
a = array([[1,2,3,4,5],
          [4,5,6,7,8],
          [8,7,4,5,2],
          [9,12,15,85,23]])
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 8,  7,  4,  5,  2],
       [ 9, 12, 15, 85, 23]])

In [35]:
a[0]

array([1, 2, 3, 4, 5])

In [36]:
a[0,0]

1

In [37]:
i = [0,1,2,3]

In [40]:
j= [1,2,3,4]

In [41]:
a[i,j]

array([ 2,  6,  5, 23])

In [42]:
a[a<8]

array([1, 2, 3, 4, 5, 4, 5, 6, 7, 7, 4, 5, 2])

In [46]:
b1 = array([True,False,False,True])
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 8,  7,  4,  5,  2],
       [ 9, 12, 15, 85, 23]])

In [45]:
a[b1,:]

array([[ 1,  2,  3,  4,  5],
       [ 9, 12, 15, 85, 23]])

In [52]:
b2 = array([True,False,True,False,True])
a

array([[ 1,  2,  3,  4,  5],
       [ 4,  5,  6,  7,  8],
       [ 8,  7,  4,  5,  2],
       [ 9, 12, 15, 85, 23]])

In [51]:
a[:,b2]

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 8,  4,  2],
       [ 9, 15, 23]])

In [58]:
from numpy import *
abs(-1)   #absolute values of a number

1

In [59]:
a = array([-1,-5.5, 2+3j])
abs(a)

array([1.        , 5.5       , 3.60555128])

In [61]:
#accumulate
from numpy import *
add.accumulate(array([1,2,3,4]))

array([ 1,  3,  6, 10], dtype=int32)

In [63]:
multiply.accumulate(array([5,3,6,7]))

array([  5,  15,  90, 630], dtype=int32)

In [64]:
substract.accumulate(array([5,3,6,8]))

NameError: name 'substract' is not defined

In [65]:
add.accumulate(array([[2,3,4],[7,8,9]]))

array([[ 2,  3,  4],
       [ 9, 11, 13]], dtype=int32)

In [66]:
multiply.accumulate(array([[2,3,4],[7,8,9]]))

array([[ 2,  3,  4],
       [14, 24, 36]], dtype=int32)

In [67]:
add.accumulate(array([[2,3,4],[7,8,9]]), axis = 0) #axis=0, each column accumulation 

array([[ 2,  3,  4],
       [ 9, 11, 13]], dtype=int32)

In [71]:
add.accumulate(array([[2,3,4],[7,8,9]]), axis = 1) #axis = 1, each row accumulation 

array([[ 2,  5,  9],
       [ 7, 15, 24]], dtype=int32)

In [75]:
from numpy import *
add(array([1,8]), array([2,5]))

array([ 3, 13])

In [76]:
add(5,5) #in a same way we can add 2 arrays as well

10

In [81]:
array([1,8]) + array([2,5])

array([ 3, 13])

In [89]:
array([[1,8],[2,3]]) * array([[2,5],[5,8]])

array([[ 2, 40],
       [10, 24]])

In [88]:
a*b

array([[ 2, 40],
       [10, 24]])

In [98]:
from numpy import *
a = array([True,False,True])
a.all()  # if all elements of a are True: return True; otherwise False

False

In [99]:
all(a) #another way to do it

False

In [95]:
a = array([1,23,3,4])
a>2

array([False,  True,  True,  True])

In [110]:
allclose(array([1e10,1e-7]), array([1.0000001e10,1e-8]))

False

In [114]:
a  =  array([1,2,3,4,5,6])
alltrue(a>0)

True

In [124]:
from numpy import *
angle(1+2j, deg = True)

63.43494882292201

In [125]:
from numpy import *
a = array([[1,2,3,4,5],[6,7,8,4,6],[2,6,3,5,7]])

In [142]:
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 4, 6],
       [2, 6, 3, 5, 7],
       [1, 2, 3, 4, 6],
       [1, 2, 3, 4, 6]])

In [143]:
append(a,[[1,2,3,4,6]], axis=0)

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 4, 6],
       [2, 6, 3, 5, 7],
       [1, 2, 3, 4, 6],
       [1, 2, 3, 4, 6],
       [1, 2, 3, 4, 6]])

In [144]:
append(a,[[15],[12],[10]], axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 5 and the array at index 1 has size 3

In [164]:
from numpy import *
def myfuct(a):
    return((a[0]+a[-1])/2)
b = array([[6,6,9],[2,5,8],[5,4,7]])
apply_along_axis(myfuct,0,b)

array([5.5, 5. , 8. ])

In [154]:
f = array([[1,2,3],[4,5,6],[7,8,9]])
f

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
f[1,0]

4